FROM node:18-alpine

# Crée le dossier de l'application
WORKDIR /usr/src/app

# Copie les fichiers de configuration
COPY package*.json ./

# Installe Express (la seule dépendance)
RUN npm install express

# Copie le reste du code
COPY server.js .

EXPOSE 8080
CMD [ "node", "server.js" ]