pipeline {
    agent any

    stages {
        stage('1. Récupération du Code') {
            steps {
                echo 'Récupération des fichiers depuis Git...'
                // Force Jenkins à récupérer le code de GitHub dans le workspace
                checkout scm
            }
        }

        stage('2. Analyse SonarQube') {
            steps {
                withSonarQubeEnv('MonSonarLocal') {
                    echo 'Simulating SonarQube Scan...'
                }
            }
        }

        stage('3. Build de l\'image Docker') {
            steps {
                echo 'Construction de l\'image...'
                // On utilise "test jenkins" sans le ./ devant pour Windows
                bat 'docker build -t mon-app-test:latest "test jenkins"'
            }
        }

        stage('4. Déploiement Local') {
            steps {
                echo 'Lancement du conteneur...'
                // Nettoyage et lancement sous Windows
                bat 'docker stop app-test-instance 2>nul || ver >nul'
                bat 'docker rm app-test-instance 2>nul || ver >nul'
                bat 'docker run -d --name app-test-instance -p 8085:8080 mon-app-test:latest'
            }
        }
    }

    post {
        always {
            echo 'Nettoyage final du workspace...'
            cleanWs()
        }
    }
}
